labels:
  0 : "unlabeled"
  1 : "outlier"
  10: "car"
  11: "bicycle"
  13: "bus"
  15: "motorcycle"
  16: "on-rails"
  18: "truck"
  20: "other-vehicle"
  30: "person"
  31: "bicyclist"
  32: "motorcyclist"
  40: "road"
  44: "parking"
  48: "sidewalk"
  49: "other-ground"
  50: "building"
  51: "fence"
  52: "other-structure"
  60: "lane-marking"
  70: "vegetation"
  71: "trunk"
  72: "terrain"
  80: "pole"
  81: "traffic-sign"
  99: "other-object"
  252: "moving-car"
  253: "moving-bicyclist"
  254: "moving-person"
  255: "moving-motorcyclist"
  256: "moving-on-rails"
  257: "moving-bus"
  258: "moving-truck"
  259: "moving-other-vehicle"


color_map: # bgr
  0 : [0, 0, 0]
  1 : [0, 0, 255]
  10: [245, 150, 100]
  11: [245, 230, 100]
  13: [250, 80, 100]
  15: [150, 60, 30]
  16: [255, 0, 0]
  18: [180, 30, 80]
  20: [255, 0, 0]
  30: [30, 30, 255]
  31: [200, 40, 255]
  32: [90, 30, 150]
  40: [255, 0, 255]
  44: [255, 150, 255]
  48: [75, 0, 75]
  49: [75, 0, 175]
  50: [0, 200, 255]
  51: [50, 120, 255]
  52: [0, 150, 255]
  60: [170, 255, 150]
  70: [0, 175, 0]
  71: [0, 60, 135]
  72: [80, 240, 150]
  80: [150, 240, 255]
  81: [0, 0, 255]
  99: [255, 255, 50]
  252: [245, 150, 100]
  256: [255, 0, 0]
  253: [200, 40, 255]
  254: [30, 30, 255]
  255: [90, 30, 150]
  257: [250, 80, 100]
  258: [180, 30, 80]
  259: [255, 0, 0]

necessary_labels: [1, 10, 11, 13, 15, 16, 18, 20, 30, 31, 32, 81, 99, 252, 253, 254, 255, 256, 257, 258, 259]

algos_params:
  'dbscan': ['eps:float', 'min_samples:int',  'algorithm:str']
  'kmeans': ['n_clusters:int', 'max_iter:int', 'n_init:int']
  'hdbscan': ['min_cluster_size:int', 'min_samples:int']
  'optics': ['min_samples:int', 'xi:float', 'min_cluster_size:int',  'metric:str', 'cluster_method:str', 'algorithm:str']
  'SpectralClustering': ['n_clusters:int', 'n_init:int', 'eigen_solver:str', 'affinity:str','assign_labels:str']

string_params:
  'SpectralClustering':
    'eigen_solver': ['arpack', 'lobpcg', 'amg']
    'affinity': ['nearest_neighbors', 'affinity', 'rbf', 'precomputed', 'precomputed_nearest_neighbors']
    'assign_labels': ['kmeans', 'discretize', 'cluster_qr']
  'optics':
    'metric': ['euclidean']
    'cluster_method': ['xi','dbscan']
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute']
  'dbscan':
    'algorithm': ['auto']
#  'kmeans':
#    'algorithm': ['lloyd']


numeric_params:
  'SpectralClustering':
    'n_clusters': [1, 50]
    'n_init': [0, 10]
  'optics':
    'min_samples': [1, 10]
    'xi': [0, 1]
    'min_cluster_size': [1, 10]
  'dbscan':
    'eps': [0.1, 1.0]
    'min_samples': [1, 10]
  'kmeans':
    'n_clusters': [20, 100]
    'max_iter': [100, 500]
  'hdbscan':
    'min_cluster_size': [1, 15]
    'min_samples': [1, 10]